### PR TITLE
Merge `web-branch` to `development` branch

### PR DESCRIPTION
**Pull request by o-rashad**
- Practicing DOM manipulation by dynamically rendering a simple restaurant homepage using :
  - Webpacker (npm package manager)
  - Vanilla Js

### CODE REVIEW

**Review by taiwo2 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED ♻️ 
@od-c0d3r well done for this project, I commend your professionalism, I saw that your project has been review but can't find the comments, however, few changes are required

- [x] It uses ES6 syntax ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/es6_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/))
  - [x] usage of arrow functions instead of the `function` keyword in your js files like in your  Home.js, contact.js,menu.js

### once specific changes are made kindly request for another review

**Comment by od-c0d3r** [comment]
Thank you @taiwo2 for the review, about the first review I already made a ticket for it. 👍🏼

**Comment by o-rashad** [comment]
Hey @taiwo2, thanks for the review.
I have made the requested changes.
about the 1st CR issue, I have opened a ticket for it.
Thank you.

**Comment by taiwo2** [comment]
> Hey @taiwo2, thanks for the review.
> I have made the requested changes.
> about the 1st CR issue, I have opened a ticket for it.
> Thank you.

Alright, thanks for the message

**Review by mke2111 — APPROVED** [review]
### Hi @od-c0d3r, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉** 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------

**Pull request merged**
